[package]
name                   = "beer-window"
version.workspace      = true
edition.workspace      = true
rust-version.workspace = true
license.workspace      = true
description            = "Platform-neutral windowing contract for the beer terminal"
readme                 = "README.md"

[dependencies]
beer-protocols.workspace         = true
smithay-client-toolkit.workspace = true

[lints]
workspace = true
