[workspace]
resolver = "3"
members = ["crates/beer", "crates/beer-protocols"]

[workspace.package]
version = "0.5.3"
edition = "2024"
rust-version = "1.95.0"
license = "EUPL-1.2"

[workspace.dependencies]
# Workspace components
beer-protocols = { path = "crates/beer-protocols", version = "0.5.3" }

# Other dependencies
anyhow = "1.0.102"
calloop = { version = "0.14.4", features = ["signals"] }
calloop-wayland-source = "0.4.1"
flate2 = "1.0.35"
fontconfig = "0.11.0"
freetype-rs = "0.38.0"
harfbuzz_rs_now = "2.3.2"
image = { version = "0.25.5", default-features = false, features = [
  "png",
  "jpeg",
  "gif",
  "bmp",
  "webp",
] }
lru = "0.18.0"
pound = "0.1.6"
rustix = { version = "1.1.4", features = [
  "pty",
  "process",
  "termios",
  "stdio",
  "fs",
  "shm",
  "mm",
] }
serde = { version = "1.0.228", features = ["derive"] }
serde_ignored = "0.1.14"
smithay-client-toolkit = "0.20.0"
thiserror = "2.0.18"
toml = "1.1.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
unicode-width = "0.2.2"
vte = "0.15.0"
wayland-client = "0.31.14"
wayland-protocols = { version = "0.32.13", features = [
  "client",
  "staging",
  "unstable",
] }

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"
missing_debug_implementations = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
